### ISSUE TITLE
Plugin appears as "Sample Plugin"

### ISSUE THREAD

**Issue by PaulAmosKreiner** [Pr0dt0s/new-note-new-window#1]
starts with "Sample Plugin installed" notification and then consistently appears as that: in preferences and also in command palette. this is on macOS.

**Comment by Pr0dt0s** [comment]
Hi @PaulAmosKreiner,

I just fixed this issue and made and published the new release, so it is already available in the obsidian plugin directory.

Thank you very much for the feedback, I really appreciate it.
