### ISSUE TITLE
My favorite Obsidian Plugin! And request.

### ISSUE THREAD

**Issue by johnsonblue75** [Pr0dt0s/new-note-new-window#3]
Hey guys, as someone who came over from OneNote after 15 years yours is my favorite most-used plugin. I love it. So helpful.

I was wondering if I can do the following and also if you can add a feature.

1) First, I'm on Windows 11 and using PowerToys (particularly its key [re]mapper feature). I changed the New Note New Window to something obscured: ctrl-shift-alt-n and then I remapped that shortcut globally to ctrl-n - so I could create a new note in a new window from anywhere. For some reason it onlky works when obsidian is at forefront (where OneNote it always worked) can you suggest a fix?
2) Can you do this: make it so you can "dock" a new note new window so the the Windows OS window pane thing where you drag a window to a part of the screen and then it docks that window there while you pick another window to open in the open space - and then you can drag a slider to reposition both windows - can you make it so that yours can work like OneNote's? I found this to be the best feature for OneNote desktop. Basically, the docked new window would not be treated as one of the windows as part of that OS window thing. Instead - it's like it's own space. And while you can independently drag that "docked" onenote window and the others will move, that onenote window is its own thing. So when you use the OS window mover thing - it ignores the OneNote window and leaves that alone. Maybe this is just too much or an operating system thing. Anyway. Fantastic plugin!!!

**Comment by Pr0dt0s** [comment]
Hi @johnsonblue75, 

Let me first thank you for your feedback, I'm really glad you liked this plugin!

I reviewed Obsidian´s plugin API but couldn't find any way to interface that deeply with the OS that could make implementing this feature possible.

You should try requesting this feature directly through [Obsidian´s forum](https://forum.obsidian.md).
