### ISSUE TITLE
Add option for Default note save location

### ISSUE THREAD

**Issue by Grant837** [Pr0dt0s/new-note-new-window#4]
It would be handy to be able to set the folder where new files are created/saved.  I want to use this plugin for taking notes while reading a webpage in my browser and just have them auto created/saved in my ´Inbox´  for later processing.

**Comment by Pr0dt0s** [comment]
Hello @Grant837,
Thanks a lot for the feedback. I just published an updated version that solves this issue, let me know if this matches your use case.

In the future I had already planned to implement something like this but with the ability to create more than one hotkey, as in one hotkey for each custom folder. But this seems like a good first step towards that.

**Comment by Grant837** [comment]
@Pr0dt0s Hey!  I for got to say "Thanks!"
